# login
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@schoolerp.com",
    "password": "Admin@123"
}

### ME
GET http://localhost:5000/api/auth/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5Ac2Nob29sZXJwLmNvbSIsInJvbGUiOiJBZG1pbmlzdHJhdG9yIiwiaWF0IjoxNzg0MTc0MzIzLCJleHAiOjE3ODQxNzc5MjN9.fURW44LJAS2mmtjXwO300iMg0-VXI9vAeurjBz9FxrM

### logout
POST http://localhost:5000/api/auth/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5Ac2Nob29sZXJwLmNvbSIsInJvbGUiOiJBZG1pbmlzdHJhdG9yIiwiaWF0IjoxNzg0MTc0MzIzLCJleHAiOjE3ODQxNzc5MjN9.fURW44LJAS2mmtjXwO300iMg0-VXI9vAeurjBz9FxrM

### create academic year
POST http://localhost:5000/api/academic-years HTTP/1.1
Content-Type: application/json

{
    "name": "2028/2029",
    "start_date": "2028-09-01",
    "end_date": "2029-06-30"
}
### Activate academic year
patch http://localhost:5000/api/academic-years/5/activate HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5Ac2Nob29sZXJwLmNvbSIsInJvbGUiOiJBZG1pbmlzdHJhdG9yIiwiaWF0IjoxNzg0MTc0MzIzLCJleHAiOjE3ODQxNzc5MjN9.fURW44LJAS2mmtjXwO300iMg0-VXI9vAeurjBz9FxrM

### complete academic year
patch http://localhost:5000/api/academic-years/3/complete HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5Ac2Nob29sZXJwLmNvbSIsInJvbGUiOiJBZG1pbmlzdHJhdG9yIiwiaWF0IjoxNzg0MTI1OTYzLCJleHAiOjE3ODQxMjk1NjN9.BzsdgV5-2DtuJTnuLCX76BvzzbChIRatIPt17_ItUZQ

### update academic year
patch http://localhost:5000/api/academic-years/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5Ac2Nob29sZXJwLmNvbSIsInJvbGUiOiJBZG1pbmlzdHJhdG9yIiwiaWF0IjoxNzg0MTc0MzIzLCJleHAiOjE3ODQxNzc5MjN9.fURW44LJAS2mmtjXwO300iMg0-VXI9vAeurjBz9FxrM
Content-Type: application/json

{
    "name": "2026/2027",
    "start_date": "2026-09-02",
    "end_date": "2027-06-30"
}

### get all academic years
GET http://localhost:5000/api/academic-years HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5Ac2Nob29sZXJwLmNvbSIsInJvbGUiOiJBZG1pbmlzdHJhdG9yIiwiaWF0IjoxNzg0MTI1OTYzLCJleHAiOjE3ODQxMjk1NjN9.BzsdgV5-2DtuJTnuLCX76BvzzbChIRatIPt17_ItUZQ

### get academic year by id
GET http://localhost:5000/api/academic-years/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5Ac2Nob29sZXJwLmNvbSIsInJvbGUiOiJBZG1pbmlzdHJhdG9yIiwiaWF0IjoxNzg0MTI1OTYzLCJleHAiOjE3ODQxMjk1NjN9.BzsdgV5-2DtuJTnuLCX76BvzzbChIRatIPt17_ItUZQ